// @generated by scripts/generate-api-types.sh; DO NOT EDIT.
// Rust serde models in crates/miao-core are the source of truth.

export type NodeType = 'hysteria2' | 'anytls' | 'ss' | 'vmess' | 'vless' | 'trojan' | 'tuic';

export type RouteMode = "rule" | "global";

export type NodeSelect = "manual" | "fastest_hk" | "fastest_jp" | "fastest_tw" | "fastest_sg" | "fastest_us";

export type RuntimePhase = "initializing" | "extracting" | "validating" | "fetching_subscriptions" | "starting" | "ready" | "refreshing_subscriptions" | "applying_config" | "reloading" | "stopping" | "stopped" | "failed";

export type RuntimeWarningSeverity = "warning" | "error" | "info";

export type RuntimeWarning = { code: string, message: string, severity: RuntimeWarningSeverity, };

export type ApiResponse<T> = { success: boolean, message: string, data?: T, };

export type StatusData = { running: boolean,
/**
 * True only after the managed sing-box instance passed its startup
 * readiness check. A spawned process may be `running` while this is false.
 */
ready: boolean, phase: RuntimePhase, initializing: boolean, route_mode: RouteMode, node_select: NodeSelect, pid?: number, uptime_secs?: number, warning?: string,
/**
 * Structured diagnostics for new clients. `warning` remains above as a
 * compatibility projection for existing panel/API consumers.
 */
warnings: Array<RuntimeWarning>, vps_supported: boolean, platform: string,
/**
 * MCP 端点（POST /mcp）开关状态
 */
mcp: boolean, };

export type ConnectivityResult = { name: string, url: string, latency_ms: number | null, success: boolean, };

export type NodeInfo = { tag: string, server: string, server_port: number, node_type: string, sni?: string, };

export type RuleInfo = { index: number, field?: string, value?: string, target?: string,
/**
 * 出口节点不存在,生成配置时被跳过(未生效)
 */
skipped: boolean, raw: string, };

export type SubscriptionState = "pending" | "refreshing" | "ready" | "failed";

export type SubStatus = { url: string, success: boolean, node_count: number,
/**
 * 该订阅被禁用的节点数（易变层 disabled_nodes 中匹配此订阅的条目数）
 */
disabled_count: number, state: SubscriptionState, error?: string, };

export type SubNodeInfo = { name: string, server: string, server_port: number, node_type: string, disabled: boolean, };

export type SubNodesInfo = { url: string, nodes: Array<SubNodeInfo>, };

export type SetNodeDisabledRequest = { sub: string, name: string, disabled: boolean, };

export type VersionInfo = { current: string, latest: string | null, has_update: boolean, download_url: string | null, upgrade_supported: boolean, };

export type SubRequest = { url: string, };

export type VergeImportItem = { name?: string, url: string, already_added: boolean, };

export type VergeImportResult = { found: boolean, items: Array<VergeImportItem>, };

export type SubBatchRequest = { urls: Array<string>, };

export type SubBatchResult = { added: number, skipped: number, };

export type RuleRequest = { field: string, value: string, target: string, };

export type DeleteRuleRequest = { index: number, raw: string, };

export type McpRequest = { enabled: boolean, };

export type RouteModeRequest = { route_mode: RouteMode, };

export type NodeSelectRequest = { node_select: NodeSelect, };

export type LastProxy = { group: string, name: string, };

export type VpsDeployRequest = { ip: string, password: string, };

export type VpsDeployResponse = { tag: string, };

export type NodeRequest = { node_type?: NodeType, tag: string, server: string, server_port: number, password?: string, uuid?: string, alter_id?: number, sni?: string, cipher?: string, skip_cert_verify?: boolean, tls_enabled?: boolean, transport_type?: string, transport_path?: string, transport_host?: string, grpc_service_name?: string, alpn?: Array<string>, client_fingerprint?: string, reality_public_key?: string, reality_short_id?: string, flow?: string, packet_encoding?: string, tuic_congestion_control?: string, tuic_udp_relay_mode?: string, tuic_zero_rtt?: boolean, obfs_type?: string, obfs_password?: string, };

export type BatchNodeRequest = { nodes: Array<NodeRequest>, };

export type BatchNodeAdded = { index: number, tag: string, };

export type BatchNodeFailure = { index: number, tag: string, message: string, };

export type BatchNodeResult = { added: Array<BatchNodeAdded>, failed: Array<BatchNodeFailure>, };

export type DeleteNodeRequest = { tag: string, };
